# Generated by Django 4.1.5 on 2023-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="url",
            field=models.SlugField(
                default=None, max_length=200, unique=True, verbose_name="Categories"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, verbose_name="name"),
        ),
    ]
