# Generated by Django 4.1.5 on 2023-02-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="url",
            field=models.SlugField(
                default=None, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_category",
                to="blog.category",
            ),
        ),
    ]
